name: "Test"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: false
      - name: "Download ShellCheck"
        uses: "robinraju/release-downloader@v1.10"
        with:
          repository: "koalaman/shellcheck"
          tag: "v0.10.0"
          filename: "shellcheck-v*.linux.x86_64.tar.xz"
          tarBall: false
          zipBall: false
      - name: "Extract ShellCheck"
        run: |
          tar xvf ./shellcheck-v*.tar.xz
          rm -v   ./shellcheck-v*.tar.xz
          mv -v   ./shellcheck-v*/shellcheck "./shellcheck"
          rm -rv  ./shellcheck-v*
          ./shellcheck --version
      - name: "ShellCheck"
        run: |
          ./shellcheck \
            --color=always \
            "distcc.sh" \
            "distcc-driver-lib.sh"

  unit_test:
    name: "Unit tests"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      - name: "Unit tests"
        run: |
          test/bash_unit/bash_unit -v
          FORCE_COLOR="true" test/bash_unit/bash_unit test/test_*
